version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - posts
      - cars
      - auth
    networks:
      - my_network

  posts:
    build: ./posts_service
    ports:
      - "5004:5004"
    networks:
      - my_network

  cars:
    build: ./cars_service
    ports:
      - "5005:5005"
    networks:
      - my_network

  auth:
    build: ./auth_service
    ports:
      - "5003:5003"
    networks:
      - my_network

networks:
  my_network:
